const users = [
  {
    name: "Fahim Ahmed",
    profile_photo: 'https://shorturl.at/oDQU6',
    post_time_ago: '2 days ago',
    post_text:'Eid Mubarak ❤️❤️',
    post_img: 'https://shorturl.at/orAWY',
    post_like: '257',
    post_comment: '46',
  },
  {
    name: "Zuma Binte Ziaa",
    profile_photo: 'https://shorturl.at/fFVW5',
    post_time_ago: 'a day ago',
    post_text:`Eid pictures 🥰😍❤️😘`,
    post_img: 'https://shorturl.at/AGQUW',
    post_like: '52',
    post_comment: '7',
  },
  {
    name: "Sheikh Taniya",
    profile_photo: 'https://shorturl.at/dhpzF',
    post_time_ago: '13 h',
    post_text:`𝐇𝐚𝐩𝐩𝐲✨ 𝐄𝐢𝐝-𝐮𝐥-𝗔𝗷𝗵𝗮 𝐀𝐧𝐝 𝐄𝐢𝐝 𝐌u𝐛𝐚𝐫𝐚𝐤!💚
    "" ~𝐓𝐚𝐤𝐚𝐛𝐛𝐚𝐥𝐚𝐥𝐥𝐚𝐡𝐮 𝐌𝐢𝐧𝐧𝐚  𝐖𝐚  𝐌𝐢𝐧𝐤𝐮𝐦 !! ✨`,
    post_img: 'https://shorturl.at/dkM78',
    post_like: '50',
    post_comment: '13',
  },
  {
    name: "N.A. Fahim",
    profile_photo: 'https://shorturl.at/azU79',
    post_time_ago: '8 hours ago',
    post_text:`২০১৯ বিশ্বকাপের স্কোয়াড থেকে বাদ পড়া ছেলেটা আজ দেশ সেরা পেইসার- দ্যা স্পীড স্টার নামে পরিচিত, ২০২৩ বিশ্বকাপে সে ছেলেটা দলে আটো চয়েস ~ তাসকিন আহমেদ।`,
    post_img: 'https://shorturl.at/mrvD9',
    post_like: '12',
    post_comment: '4',
  },
  {
    name: "Jahan Rahman Jui",
    profile_photo: 'https://shorturl.at/ivP27',
    post_time_ago: '22 June',
    post_text:`আমি চাই তুমি ভালো থাকো, প্রতিটা মূহুর্ত ভালো কাটুক।`,
    post_img: 'https://shorturl.at/lJNR8',
    post_like: '17',
    post_comment: '9',
  },
  {
    name: "Priya Jaigerdar",
    profile_photo: 'https://shorturl.at/djnE7',
    post_time_ago: '5 June',
    post_text:`Happy birthday abbu.l miss you so much.`,
    post_img: 'https://shorturl.at/koDKP',
    post_like: '123',
    post_comment: '41',
  },
  {
    name: "Abul Husen Lalon",
    profile_photo: 'https://tinyurl.com/bdzf5wt2',
    post_time_ago: 'a day ago',
    post_text:`ঈদের দিন বিকাল বেলা শাহারপাড়া বাজারে এবং রাতে নয়াবন্দর বাজারে আওয়ামিলীগ, যুবলীগ, স্বেচ্ছাসেবক লীগ, ছাত্রলীগ সহ এলাকার মুরব্বিরান ও যুবকদের সাথে শুভেচ্ছা বিনিময়ের সময় মানচেস্টার সিটি আওয়ামিলীগ সভাপতি প্রিয় বড় ভাই অয়েছ কামালী সহ আমরা সবাই আনন্দঘন সময় কাটালাম।`,
    post_img: 'https://tinyurl.com/337aax86',
    post_like: '218',
    post_comment: '56',
  },
  {
    name: "Sheikh Taniya",
    profile_photo: 'https://shorturl.at/dhpzF',
    post_time_ago: '16 h',
    post_text:`never waste anything`,
    post_img: 'https://shorturl.at/bdyP3',
    post_like: '56',
    post_comment: '4',
  },
  {
    name: "Sujel Ahmed",
    profile_photo: 'https://shorturl.at/chKSW',
    post_time_ago: '22 h',
    post_text:`Stay home be safe everyone…`,
    post_img: 'https://shorturl.at/fEGPQ',
    post_like: '24',
    post_comment: '3',
  },
  {
    name: "Adnan Akram",
    profile_photo: 'https://shorturl.at/prAFJ',
    post_time_ago: 'a day ago',
    post_text:`একদিনের কসাই হয়ে সবার সাথে ঈদ আনন্দ ভাগাভাগি করে নিলাম। বিকেলে অবশ্য ডেলিভারি বয় এর কাজও করা হয়েছে। সব মিলিয়ে আলহামদুলিল্লাহ আল্লাহতালার কাছে লাখ কোটি শুকরিয়া।`,
    post_img: 'https://shorturl.at/ksN15',
    post_like: '26',
    post_comment: '5',
  },
];


